import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,action,items,migrateState,dateKey,refreshDay} from '../engine.mjs';
import {repairNarration,cleanNarration,ensureWorld,lootDrop,finishEncounter,assignFoe,applyPaths,narrativePrompt} from '../campaign.mjs';
const now=new Date(2026,8,16,12);
const fresh=()=>{const s=initialState();s.day=dateKey(now);ensureWorld(s);return s;};
test('equipment gates, cooldown and no duplicates',()=>{const s=fresh();for(let i=0;i<7;i++)assert.equal(lootDrop(s,items,()=>0),null);const first=lootDrop(s,items,()=>0);assert.equal(first.rarity,'Uncommon');for(let i=0;i<4;i++)assert.equal(lootDrop(s,items,()=>0),null);const second=lootDrop(s,items,()=>0);assert.notEqual(first.id,second.id);s.world.totalWins=23;s.world.loot.lastDrop=0;assert.equal(lootDrop(s,items.filter(i=>i.rarity==='Rare'),()=>0),null);assert.equal(lootDrop(s,items.filter(i=>i.rarity==='Rare'),()=>0).rarity,'Rare');s.world.totalWins=58;s.world.loot.lastDrop=0;assert.equal(lootDrop(s,items.filter(i=>i.rarity==='Epic'),()=>0),null);assert.equal(lootDrop(s,items.filter(i=>i.rarity==='Epic'),()=>0).rarity,'Epic');assert.equal(new Set(s.inventory).size,s.inventory.length);});
test('thirty eligible misses guarantee lowest available tier',()=>{const s=fresh();s.world.totalWins=7;for(let i=0;i<29;i++)assert.equal(lootDrop(s,items,()=>.99),null);assert.equal(lootDrop(s,items,()=>.99).rarity,'Uncommon');assert.equal(s.world.loot.dry,0);});
test('migration preserves existing loot and starts cooldown from prior wins',()=>{const s=initialState();s.inventory=items.slice(0,5).map(i=>i.id);s.tasks[0].wins=40;const before=[...s.inventory];migrateState(s);assert.deepEqual(s.inventory,before);assert.equal(s.world.totalWins,40);assert.equal(lootDrop(s,items,()=>0),null);});
test('travel changes region without rewards, rejects unknown routes and active combat',()=>{const s=fresh();action(s,{type:'travel',id:'place-1'},now);assert.equal(s.world.location,'place-1');assert.equal(s.xp,0);assert.equal(s.world.mission.progress,0);assert.throws(()=>action(s,{type:'travel',id:'fake'},now));action(s,{type:'start'},now);assert.throws(()=>action(s,{type:'travel',id:'place-2'},now));});
test('daily discovery happens once per date without missed-day catchup',()=>{const s=fresh();refreshDay(s,new Date(2026,8,18,12));assert.equal(s.world.locations.length,4);refreshDay(s,new Date(2026,8,18,15));assert.equal(s.world.locations.length,4);});
test('six completed tasks conclude mission once; three paths preserve relationships',()=>{const s=fresh(),t=s.tasks[0];assert.throws(()=>action(s,{type:'path',id:'no'},now));for(let i=0;i<6;i++)finishEncounter(s,t,()=>.9);assert.equal(s.world.mission.status,'complete');assert.equal(s.world.paths.length,3);assert.equal(s.world.chapters.length,1);finishEncounter(s,t,()=>.9);assert.equal(s.world.chapters.length,1);const r=structuredClone(s.world.relationships);const p=s.world.paths[1];action(s,{type:'path',id:p.id},now);assert.equal(s.world.chapter,2);assert.equal(s.world.mission.progress,0);assert.equal(s.world.mission.title,p.title);assert.deepEqual(s.world.relationships,r);assert.equal(s.xp,0);});
test('parley creates friend then ally; recurring allies retain identity',()=>{const s=fresh(),t=s.tasks[1];s.world.approach='parley';finishEncounter(s,t,()=>.4);const id=t.foeId;assert.equal(s.world.relationships[id].status,'friend');finishEncounter(s,t,()=>.4);assert.equal(s.world.relationships[id].status,'ally');s.world.approach='fight';finishEncounter(s,t,()=>.99);assert.equal(s.world.relationships[id].status,'ally');assert.equal(assignFoe(s,t).id,id);});
test('chapter choice unlock and dedupe; focus beats do not reward or advance',()=>{const s=fresh();assert.throws(()=>action(s,{type:'story-choice',value:'help'},now));s.world.mission.progress=2;action(s,{type:'story-choice',value:'help'},now);assert.throws(()=>action(s,{type:'story-choice',value:'help'},now));action(s,{type:'start'},now);assert.throws(()=>action(s,{type:'focus-beat'},new Date(+now+60000)));action(s,{type:'focus-beat'},new Date(+now+300000));assert.throws(()=>action(s,{type:'focus-beat'},new Date(+now+300001)));assert.equal(s.xp,0);assert.equal(s.world.mission.progress,2);action(s,{type:'pause'},new Date(+now+310000));assert.throws(()=>action(s,{type:'focus-beat'},new Date(+now+600000)));});
test('model paths validate schema, retain mechanical fields and reject stale chapters',()=>{const s=fresh();for(let i=0;i<6;i++)finishEncounter(s,s.tasks[0],()=>.8);const original=structuredClone(s.world.paths);assert.equal(applyPaths(s,1,'{"paths":[]}'),false);const json=JSON.stringify({paths:original.map((p,i)=>({title:`Mission ${i}`,hook:'A mysterious path.',target:1}))});assert.equal(applyPaths(s,2,json),false);assert.equal(applyPaths(s,1,json),true);assert.equal(s.world.paths[0].target,original[0].target);assert.equal(s.world.paths[0].id,original[0].id);s.backstory='Former lighthouse keeper';const prompt=narrativePrompt(s,s.world.beats[0]);assert.ok(prompt.prompt.includes(s.backstory));assert.ok(prompt.prompt.includes('defeated'));assert.ok(prompt.system.includes('maximum 50 words'));});

test('narration rejects context echoes and oversized responses',()=>{assert.throws(()=>cleanNarration('"},"chapter":1,"mission":{"title":"test"}'));assert.throws(()=>cleanNarration('word '.repeat(70)));assert.equal(cleanNarration('‐\nThe lantern lights a winding path.'),'The lantern lights a winding path.');});

test('one-word model responses and unfinished fragments never replace narration',()=>{for(const text of ['Computer','computer','Computer.','The lantern lights a winding path but'])assert.throws(()=>cleanNarration(text));assert.equal(cleanNarration('The lantern lights a winding path.'),'The lantern lights a winding path.');});
test('migration repairs already saved invalid opening without changing progress',()=>{const s=fresh(),b=s.world.beats[0];delete b.fallbackText;b.text='Computer';b.source='local model';s.story='Computer';s.xp=123;s.inventory=['moss-cloak'];migrateState(s);assert.match(b.text,/morning bell/);assert.equal(s.story,b.text);assert.equal(b.source,'built-in');assert.equal(b.status,'fallback');assert.equal(s.xp,123);assert.deepEqual(s.inventory,['moss-cloak']);});
test('new beats retain original prose for recovery after invalid model output',()=>{const s=fresh(),b=s.world.beats[0],original=b.text;b.text='Computer';b.source='local model';repairNarration(s);assert.equal(b.text,original);assert.equal(b.fallbackText,original);});
