import test from 'node:test';
import assert from 'node:assert/strict';
import {createClient,storeDraft,readDraft,clearDraft} from '../public/connection.js';
const response=(status,data)=>({status,ok:status===200,json:async()=>data});
test('a stale session token reconnects and retries a rejected request once',async()=>{const requests=[];let token='first',reject=true;const client=createClient({fetcher:async(url,options)=>{if(url==='/api/state')return response(200,{token,serverBuild:'a'});requests.push(options.headers['X-Sidequest-Token']);if(reject){reject=false;token='second';return response(403,{error:'expired'});}return response(200,{ok:true});}});await client.refresh();assert.deepEqual(await client.request('action',{type:'add'}),{ok:true});assert.deepEqual(requests,['first','second']);});
test('a network failure never automatically replays a possibly committed mutation',async()=>{let writes=0;const events=[];const client=createClient({onConnection:s=>events.push(s),fetcher:async(url)=>{if(url==='/api/state')return response(200,{token:'a',serverBuild:'a'});writes++;throw Error('connection lost');}});await assert.rejects(client.request('action',{type:'complete'}),/Connection interrupted/);assert.equal(writes,1);assert.equal(events.at(-1),'offline');});
test('new builds show a reload notice even after session refresh',async()=>{let build='old';const events=[];const client=createClient({onConnection:s=>events.push(s),fetcher:async()=>response(200,{token:'x',serverBuild:build})});await client.refresh();build='new';await client.refresh();assert.deepEqual(events,['ready','update']);});
test('onboarding draft round-trips independently of the shared save',()=>{const map=new Map();const storage={getItem:k=>map.get(k),setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};const value={draft:{name:'Nova',backstory:'A lunar mechanic',appearance:{hairStyle:'bob'},settings:{world:'A space station',model:'local'}},step:2,onboarding:true,profileRevision:7};storeDraft(storage,value);assert.deepEqual(readDraft(storage),value);clearDraft(storage);assert.equal(readDraft(storage),null);});
test('a model response cannot clear a pending update notice',async()=>{let build='old';const events=[];const client=createClient({onConnection:s=>events.push(s),fetcher:async url=>url==='/api/state'?response(200,{token:'x',serverBuild:build}):response(200,{text:'hello'})});await client.refresh();build='new';await client.refresh();await client.request('model-test',{});assert.equal(events.at(-1),'update');});
