import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {once} from 'node:events';
import http from 'node:http';
async function start(dir){const child=spawn(process.execPath,['server.mjs'],{cwd:new URL('..',import.meta.url),env:{...process.env,SIDEQUEST_DATA_DIR:dir,PORT:'0'},stdio:['ignore','pipe','pipe']});let output='';const url=await new Promise((resolve,reject)=>{child.stdout.on('data',chunk=>{output+=chunk;const match=output.match(/http:\/\/127.0.0.1:\d+/);if(match)resolve(match[0]);});child.on('exit',code=>reject(Error('Server exited: '+code)));child.on('error',reject);});return {child,url};}
async function stop(child){const exit=once(child,'exit');child.kill('SIGTERM');await exit;}
test('HTTP actions require a token, persist across restarts, and escape no secrets into saves',async()=>{const dir=await mkdtemp(join(tmpdir(),'sidequest-test-'));let server;try{server=await start(dir);const initial=await (await fetch(server.url+'/api/state')).json();let response=await fetch(server.url+'/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:'{"type":"add","title":"Unauthorized"}'});assert.equal(response.status,403);response=await fetch(server.url+'/api/action',{method:'POST',headers:{'Content-Type':'application/json','X-Sidequest-Token':initial.token},body:JSON.stringify({type:'add',title:'Persist this quest'})});assert.equal(response.status,200);const state=await response.json();assert.ok(state.tasks.some(t=>t.title==='Persist this quest'));assert.equal(state.token,undefined);const saved=JSON.parse(await readFile(join(dir,'save.json'),'utf8'));assert.equal(saved.token,undefined);assert.equal(saved.linearKey,undefined);await stop(server.child);server=await start(dir);const restored=await (await fetch(server.url+'/api/state')).json();assert.ok(restored.tasks.some(t=>t.title==='Persist this quest'));assert.notEqual(restored.token,initial.token);response=await fetch(server.url+'/../server.mjs');assert.equal(response.status,404);const status=await new Promise((resolve,reject)=>{const req=http.get(server.url+'/api/state',{headers:{Host:'attacker.example'}},res=>{res.resume();resolve(res.statusCode);});req.on('error',reject);});assert.equal(status,403);}finally{if(server?.child&&!server.child.killed)await stop(server.child);await rm(dir,{recursive:true,force:true});}});

test('two windows cannot silently overwrite each other’s saved profile',async()=>{const dir=await mkdtemp(join(tmpdir(),'sidequest-windows-'));let server;try{server=await start(dir);const a=await(await fetch(server.url+'/api/state')).json();const b=await(await fetch(server.url+'/api/state')).json();const post=(body)=>fetch(server.url+'/api/action',{method:'POST',headers:{'Content-Type':'application/json','X-Sidequest-Token':a.token},body:JSON.stringify(body)});let response=await post({type:'settings',name:'Nova',backstory:'A moon mechanic',expectedProfileRevision:a.profileRevision});assert.equal(response.status,200);const first=await response.json();assert.equal(first.profileRevision,a.profileRevision+1);assert.ok(first.revision>a.revision);response=await post({type:'settings',name:'Outdated Rowan',expectedProfileRevision:b.profileRevision});assert.equal(response.status,409);const latest=await(await fetch(server.url+'/api/state')).json();assert.equal(latest.name,'Nova');assert.equal(latest.backstory,'A moon mechanic');assert.equal(latest.revision,first.revision);response=await post({type:'settings',name:'Nova II',expectedProfileRevision:latest.profileRevision});assert.equal(response.status,200);assert.equal((await response.json()).name,'Nova II');}finally{if(server?.child&&!server.child.killed)await stop(server.child);await rm(dir,{recursive:true,force:true});}});

test('background narration preserves newer actions and delivers three chapter paths',async()=>{const {writeFile}=await import('node:fs/promises');const {initialState,migrateState}=await import('../engine.mjs');const dir=await mkdtemp(join(tmpdir(),'sidequest-story-'));const requests=[];const model=http.createServer(async(req,res)=>{let raw='';for await(const chunk of req)raw+=chunk;const data=JSON.parse(raw);requests.push(data);const prompt=data.messages[1].content;const content=data.response_format?JSON.stringify({paths:[{title:'Rescue the signal',hook:'A friend needs help.'},{title:'The secret map',hook:'A rival has a clue.'},{title:'Beyond the clouds',hook:'Find the lost observatory.'}]}):prompt.includes('EVENT TO NARRATE: conclusion')?'The dawn returns. Your chapter is complete.':'Computer';setTimeout(()=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{message:{content}}]}));},40);});model.listen(0,'127.0.0.1');await once(model,'listening');let server;try{const s=migrateState(initialState());s.onboardingComplete=true;s.backstory='A former clock keeper';s.settings={...s.settings,restOverride:true,useModel:true,provider:'compatible',providerPort:model.address().port,model:'test'};s.world.mission.progress=5;await writeFile(join(dir,'save.json'),JSON.stringify(s));server=await start(dir);const get=async()=>await(await fetch(server.url+'/api/state')).json();let state=await get();const token=state.token;const post=async type=>{const r=await fetch(server.url+'/api/action',{method:'POST',headers:{'Content-Type':'application/json','X-Sidequest-Token':token},body:JSON.stringify({type})});assert.equal(r.status,200);return r.json();};await post('start');state=await post('complete');const xp=state.xp;for(let i=0;i<100&&state.world.pathsStatus!=='local model';i++){await new Promise(r=>setTimeout(r,20));state=await get();}assert.equal(state.world.pathsStatus,'local model');assert.equal(state.world.paths.length,3);assert.equal(state.world.paths[0].title,'Rescue the signal');assert.equal(state.story,'The dawn returns. Your chapter is complete.');assert.equal(state.xp,xp);assert.equal(state.world.mission.progress,6);assert.equal(state.world.beats[0].source,'local model');const opening=state.world.beats.find(b=>b.kind==='start');assert.equal(opening.status,'fallback');assert.equal(opening.text,opening.fallbackText);assert.notEqual(opening.text,'Computer');assert.ok(requests.some(r=>r.messages[1].content.includes(s.backstory)));}finally{if(server?.child&&!server.child.killed)await stop(server.child);model.closeAllConnections();await new Promise(r=>model.close(r));await rm(dir,{recursive:true,force:true});}});

test('companion background responses cannot replace a newer request',async()=>{const {writeFile}=await import('node:fs/promises');const {initialState,migrateState}=await import('../engine.mjs');const {chapterReward}=await import('../squad.mjs');const dir=await mkdtemp(join(tmpdir(),'sidequest-support-'));let received=[];const model=http.createServer(async(req,res)=>{let raw='';for await(const chunk of req)raw+=chunk;const payload=JSON.parse(raw),context=JSON.parse(payload.messages[1].content);received.push(context);const text=context.request==='big'?'Start with one tiny piece of work.':'Write down the distraction and choose one small action.';setTimeout(()=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{message:{content:text}}]}));},50);});model.listen(0,'127.0.0.1');await once(model,'listening');let server;try{const s=migrateState(initialState());chapterReward(s,{chapter:1,title:'A friend arrives'},()=>.5);Object.assign(s.squad.pets[0],{name:'Miso',personality:'Quiet and kind',style:'direct'});Object.assign(s.settings,{useModel:true,provider:'compatible',providerPort:model.address().port,model:'test'});await writeFile(join(dir,'save.json'),JSON.stringify(s));server=await start(dir);const get=async()=>await(await fetch(server.url+'/api/state')).json();let state=await get();const token=state.token;const post=reason=>fetch(server.url+'/api/action',{method:'POST',headers:{'Content-Type':'application/json','X-Sidequest-Token':token},body:JSON.stringify({type:'support',reason})});await post('big');await post('distracted');for(let i=0;i<100;i++){state=await get();if(!state.squad.support.message.pending)break;await new Promise(r=>setTimeout(r,20));}assert.equal(state.squad.support.message.text,'Write down the distraction and choose one small action.');assert.equal(state.squad.support.message.source,'local model');assert.equal(state.xp,0);assert.equal(received.at(-1).companion.name,'Miso');assert.equal(received.at(-1).companion.personality,'Quiet and kind');}finally{if(server?.child&&!server.child.killed)await stop(server.child);model.closeAllConnections();await new Promise(r=>model.close(r));await rm(dir,{recursive:true,force:true});}});
