import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,migrateState,action,fallbackStory} from '../engine.mjs';
import {hairstyles,normalizeAppearance} from '../public/character.js';
import {discoverProvider,generateLocal,storyPrompt,providerConfig} from '../providers.mjs';
const json=(value,status=200)=>({ok:status===200,status,json:async()=>value});
test('existing saves acquire onboarding fields without losing progress',()=>{const s=initialState();s.xp=210;s.inventory=['moss-cloak'];delete s.appearance;delete s.onboardingComplete;delete s.settings.provider;delete s.settings.providerPort;migrateState(s);assert.equal(s.xp,210);assert.deepEqual(s.inventory,['moss-cloak']);assert.equal(s.onboardingComplete,false);assert.equal(s.settings.provider,'ollama');assert.equal(s.appearance.hairStyle,'crop');});
test('ten distinct hairstyle silhouettes and validated colors',()=>{assert.equal(hairstyles.length,10);assert.equal(new Set(hairstyles.map(h=>JSON.stringify(h.pixels))).size,10);assert.equal(normalizeAppearance({hairColor:'red;bad',hairStyle:'unknown'}).hairStyle,'crop');assert.equal(normalizeAppearance({pantsColor:'#ffab12'}).pantsColor,'#ffab12');});
test('onboarding persists personalization and backstory influences both story modes',()=>{const s=initialState();action(s,{type:'settings',name:'Finch',backstory:'A librarian seeking a stolen book.',appearance:{hairStyle:'braids',shirtColor:'#334455'},onboardingComplete:true});assert.equal(s.onboardingComplete,true);assert.equal(s.appearance.hairStyle,'braids');assert.match(fallbackStory(s,s.tasks[0]),/librarian/);const prompt=JSON.parse(storyPrompt(s,s.tasks[0]).prompt);assert.equal(prompt.adventurer.name,'Finch');assert.match(prompt.adventurer.backstory,/stolen book/);assert.throws(()=>action(s,{type:'settings',name:' '}));});
test('Ollama discovery returns models and flags cloud models',async()=>{const p=await discoverProvider('ollama',11434,'',async url=>{assert.match(url,/127\.0\.0\.1:11434\/api\/tags/);return json({models:[{name:'small:local'},{name:'large:cloud'}]});});assert.equal(p.status,'ready');assert.equal(p.models[1].remote,true);});
test('LM Studio native discovery filters embedding models and uses loaded instance ids',async()=>{const p=await discoverProvider('lmstudio',1234,'',async()=>json({models:[{type:'llm',key:'small-chat',display_name:'Small Chat',loaded_instances:[{id:'small-chat-loaded'}]},{type:'embedding',key:'embeddings'}]}));assert.equal(p.models.length,1);assert.equal(p.models[0].id,'small-chat-loaded');});
test('LM Studio older API falls back, but auth failure does not',async()=>{let calls=0;const p=await discoverProvider('lmstudio',1234,'',async()=>++calls===1?json({},404):json({data:[{id:'local-chat'}]}));assert.equal(p.status,'ready');assert.equal(calls,2);calls=0;const auth=await discoverProvider('lmstudio',1234,'',async()=>{calls++;return json({},401);});assert.equal(auth.status,'auth');assert.equal(calls,1);});
test('discovery distinguishes empty servers and offline servers',async()=>{assert.equal((await discoverProvider('ollama',11434,'',async()=>json({models:[]}))).status,'empty');assert.equal((await discoverProvider('ollama',11434,'',async()=>{throw Error('offline');})).status,'offline');assert.throws(()=>providerConfig('unknown',1234));assert.throws(()=>providerConfig('lmstudio','https://remote.com'));});
test('generation routes to selected provider with backstory and session token',async()=>{const s=initialState();s.backstory='A librarian.';s.settings={...s.settings,model:'chat',provider:'lmstudio',providerPort:1234};const text=await generateLocal(s.settings,storyPrompt(s,s.tasks[0]),'session-secret',async(url,options)=>{assert.equal(url,'http://127.0.0.1:1234/v1/chat/completions');assert.equal(options.headers.Authorization,'Bearer session-secret');assert.match(JSON.parse(options.body).messages[1].content,/librarian/);return json({choices:[{message:{content:'The book opens.'}}]});});assert.equal(text,'The book opens.');});
test('Ollama generation uses its native protocol',async()=>{const s=initialState();s.settings.model='tiny';assert.equal(await generateLocal(s.settings,storyPrompt(s,s.tasks[0]),'',async(url,options)=>{assert.match(url,/api\/generate$/);assert.equal(JSON.parse(options.body).stream,false);return json({response:'Welcome home.'});}),'Welcome home.');});

import {onboardingPrompt,assertProfileVersion} from '../settings.mjs';
test('preview uses the latest unsaved draft, not the saved world or a fixed forest',()=>{const s=initialState();const context=JSON.parse(onboardingPrompt(s,{name:'Nova',backstory:'A mechanic on a lunar station.',world:'A tiny space station orbiting Saturn.'}).prompt);assert.equal(context.adventurer.name,'Nova');assert.match(context.adventurer.backstory,/lunar station/);assert.match(context.world,/Saturn/);assert.doesNotMatch(context.world,/woodland/);assert.equal(s.name,'Rowan');assert.equal(s.backstory,'');});
test('stale or unversioned settings drafts are rejected, ordinary game actions remain valid',()=>{const s={profileRevision:4};assert.throws(()=>assertProfileVersion(s,{type:'settings',name:'Old',expectedProfileRevision:3}),e=>e.status===409);assert.throws(()=>assertProfileVersion(s,{type:'settings',name:'Old'}),e=>e.status===409);assert.doesNotThrow(()=>assertProfileVersion(s,{type:'settings',name:'New',expectedProfileRevision:4}));assert.doesNotThrow(()=>assertProfileVersion(s,{type:'complete'}));assert.doesNotThrow(()=>assertProfileVersion(s,{type:'settings',settings:{sound:true}}));});
