import {ensureCalendar,calendarAction,createMeetingQuests} from './calendar.js';
import {ensureLore,loreAction} from './lore.js';
import {ensureSquad,squadAction,squadVictory,syncLeader} from './squad.js';
import {repairNarration,ensureWorld,newWorldDay,assignFoe,lootDrop,finishEncounter,worldAction,actionBeat} from './campaign.js';
import {normalizeAppearance,defaultAppearance} from './character.js';
import {providerConfig,cleanProviderUrl} from './providers.js';
import { randomUUID, randomInt } from './rand.js';
export const dateKey = (d = new Date()) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export const items = [
 {id:'fern-crown',name:'Fernkeeper crown',kind:'hat',color:'#a2ca86',rarity:'Uncommon',description:'A quiet promise to the paths less traveled.'},
 {id:'tide-cloak',name:'Tideglass mantle',kind:'cloak',color:'#77b8c5',rarity:'Rare',description:'Woven from mist at the edge of the sea.'},
 {id:'frost-blade',name:'Frostbell saber',kind:'weapon',color:'#d1f3ef',rarity:'Rare',description:'Its gentle chime remembers every mountain crossed.'},
 {id:'amber-crown',name:'Amber diadem',kind:'hat',color:'#e7a664',rarity:'Rare',description:'The desert keeps its smallest wonders safe.'},
 {id:'dusk-cloak',name:'Constellation cape',kind:'cloak',color:'#aa80ce',rarity:'Epic',description:'A night sky for the shoulders of a patient adventurer.'},
 {id:'dawn-blade',name:'Dawnbringer',kind:'weapon',color:'#ffe39d',rarity:'Epic',description:'Not every legend begins with a grand gesture.'},
 {id:'moss-cloak',name:'Mossweave cloak',kind:'cloak',color:'#88b98b',rarity:'Uncommon',description:'A little piece of the forest. Equippable appearance.'},
 {id:'ember-blade',name:'Ember blade',kind:'weapon',color:'#f7a666',rarity:'Rare',description:'Forged from the tasks you thought you couldn’t do.'},
 {id:'moon-cloak',name:'Moonlit cloak',kind:'cloak',color:'#aaa0e2',rarity:'Rare',description:'For the adventurer who finds their own way.'},
 {id:'sun-crown',name:'Sunpetal crown',kind:'hat',color:'#f7d778',rarity:'Epic',description:'Small victories bloom into something wonderful.'},
 {id:'star-blade',name:'Starlight sword',kind:'weapon',color:'#b4e6fa',rarity:'Epic',description:'A tiny constellation at your side.'},
];
const foes = ['The Tanglevine','The Scope Creep','The Almost-Done Wisp','The Inbox Imp','The Dread of Starting'];
export function quest(title, extra={}) { return {id:randomUUID(),title,description:'',priority:3,minutes:25,recurring:false,source:'local',foe:foes[randomInt(foes.length)],encounters:0,wins:0,rerolls:0,status:'open',intel:'',createdAt:Date.now(),...extra}; }
export function initialState(){ const tasks=[quest('Tackle that one thing you’ve been avoiding',{description:'An example quest. Rename it or add your own. Start with one small, concrete step.',priority:2,foe:'The Tanglevine'}),quest('Clear a little space in your inbox',{description:'An example daily rival. Deal with just five messages to win this round.',recurring:true,minutes:15,foe:'The Inbox Imp'}),quest('Make room for tomorrow',{description:'An example quest. Leave yourself a short note about what comes next.',minutes:10,priority:4,foe:'The Almost-Done Wisp'})]; return {version:1,day:dateKey(),name:'Rowan',backstory:'',appearance:{...defaultAppearance},onboardingComplete:false,xp:0,gold:0,energy:100,tasks,selected:tasks[0].id,battle:null,inventory:[],potions:3,equipped:{},journal:[],settings:{world:'A cozy woodland of overgrown ruins, mischievous forest creatures, and small acts of courage. Warm, witty, a little magical. Every small victory matters.',model:'',provider:'ollama',providerPort:11434,useModel:false,startHour:9,endHour:18,weekends:true,restOverride:false,sound:false},story:null,lastReward:null}; }
export function migrateState(s){s.version=7;ensureCalendar(s);ensureLore(s);ensureWorld(s);repairNarration(s);ensureSquad(s);s.profileRevision??=0;s.revision??=0;s.appearance=normalizeAppearance(s.appearance);s.backstory??='';s.onboardingComplete??=false;s.settings.provider??='ollama';s.settings.providerPort??=11434;return s;}
export function levelFor(xp){ let level=1,remaining=xp,needed=120;while(remaining>=needed){remaining-=needed;level++;needed=120+(level-1)*40;} return {level,remaining,needed}; }
export function resting(s,now=new Date()){return !s.settings.restOverride && ((s.settings.weekends && [0,6].includes(now.getDay()))||now.getHours()<s.settings.startHour||now.getHours()>=s.settings.endHour);}
export function refreshDay(s,now=new Date()){createMeetingQuests(s,quest,now);ensureWorld(s);ensureSquad(s);const today=dateKey(now); if(s.day!==today){s.squad.support.energy='unset';s.squad.support.nextAt=null;s.squad.support.message=null;s.day=today;s.energy=100;s.settings.restOverride=false;s.battle=null;for(const t of s.tasks)if(t.recurring&&t.status==='done')t.status='open';s.story=null;s.lastReward=null;if(!s.tasks.some(t=>t.id===s.selected&&t.status==='open'))s.selected=orderedTasks(s)[0]?.id||null;}newWorldDay(s);if(s.battle&&!s.battle.pausedAt&&s.squad.support.interval&&!s.squad.support.nextAt)s.squad.support.nextAt=now.getTime()+s.squad.support.interval*60000;if(resting(s,now)&&s.battle&&!s.battle.pausedAt)s.battle.pausedAt=now.getTime();}
export function orderedTasks(s){return s.tasks.filter(t=>t.status==='open').sort((a,b)=>(a.priority||5)-(b.priority||5)||(a.sortOrder??a.createdAt)-(b.sortOrder??b.createdAt));}
export function fallbackStory(s,t,mode='start'){ const openings=['A rustle in the undergrowth.','The path takes an unexpected turn.','Something stirs beneath the old bridge.'];const rivalry=t.wins?` ${t.foe} recognizes you. “You again?”`:''; const world=s.settings.world.trim().split(/[.!?]/)[0].slice(0,100);return `${openings[t.rerolls%openings.length]} ${t.foe} guards the next step.${rivalry} ${mode==='reroll'?'A different route appears. ':''}${s.name}, your move: ${t.title.replace(/[.!?]$/,'')}. One small step is enough to begin.${s.backstory?' You remember your beginnings: '+s.backstory.trim().split(/[.!?]/)[0].slice(0,90)+'.':''}\nWorld: ${world}.`; }
function requireQuest(s,id){const t=s.tasks.find(x=>x.id===(id||s.selected));if(!t)throw Error('Choose a quest first.');return t;}
function entry(s,text,kind='event'){s.journal.unshift({id:randomUUID(),text,kind,at:Date.now()});s.journal=s.journal.slice(0,200);}
export function action(s,a,now=new Date()) { refreshDay(s,now); let t;if(calendarAction(s,a,quest,now))return s;if(loreAction(s,a)){syncLeader(s);return s;}if(squadAction(s,a,now))return s;if(worldAction(s,a,now))return s;
 switch(a.type){
 case 'add': {const title=String(a.title||'').trim().slice(0,180);if(!title)throw Error('Give your quest a name.');const n=quest(title,{description:String(a.description||'').slice(0,4000),priority:[1,2,3,4].includes(+a.priority)?+a.priority:3,minutes:Math.max(1,Math.min(120,+a.minutes||25)),recurring:!!a.recurring,intel:String(a.intel||'').slice(0,1000)});s.tasks.push(n);if(!s.battle){s.selected=n.id;s.story=null;s.lastReward=null;}break;}
 case 'select':t=requireQuest(s,a.id);assignFoe(s,t);if(s.battle&&s.battle.taskId!==t.id)throw Error('Retreat from your current battle before choosing another.');s.selected=t.id;s.story=null;s.lastReward=null;break;
 case 'start':t=requireQuest(s);if(resting(s,now))throw Error('You’re at camp. Choose “Adventure anyway” if you want to play.');if(t.status!=='open')throw Error('That quest is already complete.');if(s.battle)throw Error('A battle is already underway.');assignFoe(s,t);t.encounters++;s.squad.support.nextAt=s.squad.support.interval?now.getTime()+s.squad.support.interval*60000:null;s.squad.support.message=null;s.battle={taskId:t.id,startedAt:now.getTime(),pausedAt:null,pausedMs:0,breakUntil:null,prompted:false};s.story=fallbackStory(s,t);s.lastReward=null;break;
 case 'pause':if(s.battle){if(s.battle.pausedAt){if(s.squad.support.nextAt)s.squad.support.nextAt+=now.getTime()-s.battle.pausedAt;s.battle.pausedMs+=now.getTime()-s.battle.pausedAt;s.battle.pausedAt=null;}else{s.battle.pausedAt=now.getTime();s.battle.breakUntil=null;}}break;
 case 'flee':if(s.battle){t=requireQuest(s,s.battle.taskId);entry(s,`A tactical retreat from ${t.foe}. The path will wait.`);s.battle=null;s.story='You slip back to the clearing. A different approach can wait for another moment. No progress lost.';}break;
 case 'reroll':t=requireQuest(s);t.rerolls++;s.story=fallbackStory(s,t,'reroll');break;
 case 'complete': { if(!s.battle)throw Error('Start a battle first.');t=requireQuest(s,s.battle.taskId);if(t.status!=='open')throw Error('Already completed.');const before=levelFor(s.xp).level;const xp=randomInt(25,46)+(5-(t.priority||4))*8;const gold=randomInt(5,16);const drop=lootDrop(s,[...items,...s.squad.chapterItems]);const supply=!drop&&randomInt(100)<12&&s.potions<9?'Restoration tea':null;if(supply)s.potions++;s.xp+=xp;s.gold+=gold;s.energy=Math.max(20,s.energy-10);t.status='done';t.wins++;t.completedDay=s.day;s.battle=null;const after=levelFor(s.xp).level;s.lastReward={xp,gold,item:drop,supply,levelUp:after>before,level:after};s.story=`${t.foe} yields. The clearing feels a little brighter. You did the thing. That counts.`;entry(s,`${t.title} · +${xp} XP · ${drop?.name||supply||'a step forward'}${after>before?` · Level ${after}!`:''}`,'victory');finishEncounter(s,t);squadVictory(s,xp);break; }
 case 'next':if(s.battle)throw Error('Finish or retreat from your current battle first.');s.selected=orderedTasks(s)[0]?.id||null;if(s.selected)assignFoe(s,requireQuest(s));s.story=null;s.lastReward=null;break;
 case 'heal':if(s.potions<1)throw Error('No tea left. A free pause is always available.');if(!s.battle)throw Error('Save your tea for a battle.');s.potions--;s.energy=Math.min(100,s.energy+30);if(!s.battle.pausedAt)s.battle.pausedAt=now.getTime();s.battle.breakUntil=now.getTime()+5*60000;s.battle.prompted=true;s.story='A warm cup. A deep breath. Take five minutes; resume whenever you feel ready.';entry(s,'Used restoration tea. Rest is part of the adventure.');break;
 case 'cast':{const level=levelFor(s.xp).level;if(level<2)throw Error('Unlock Scout’s Sight at level 2.');t=requireQuest(s);s.story=`Scout’s Sight reveals a path: ${t.intel||'Write down the smallest next action. Set a five-minute timer. Do only that part.'}`;break;}
 case 'equip':{const item=[...items,...s.squad.chapterItems].find(i=>i.id===a.id);if(!item||!s.inventory.includes(item.id))throw Error('Find this item on a quest first.');s.equipped[item.kind]=s.equipped[item.kind]===item.id?null:item.id;s.equipped[item.kind+'Color']=s.equipped[item.kind]?item.color:null;break;}
 case 'edit':t=requireQuest(s,a.id);if(a.title!==undefined){const title=String(a.title).trim().slice(0,180);if(!title)throw Error('Give your quest a name.');t.title=title;}if(a.priority!==undefined){if(![1,2,3,4].includes(+a.priority))throw Error('Choose a priority.');t.priority=+a.priority;t.priorityOverride=true;}if(a.intel!==undefined)t.intel=String(a.intel).slice(0,1000);if(a.description!==undefined)t.description=String(a.description).slice(0,4000);break;
 case 'archive':t=requireQuest(s,a.id);if(s.battle?.taskId===t.id)throw Error('Retreat before archiving this quest.');t.status='archived';if(s.selected===t.id){s.selected=orderedTasks(s)[0]?.id||null;s.story=null;}break;
 case 'settings': {const v=a.settings||{};
 if(a.name!==undefined&&!String(a.name).trim())throw Error('Your adventurer needs a name.');
 if(a.appearance!==undefined)s.appearance=normalizeAppearance(a.appearance);
 if(a.backstory!==undefined)s.backstory=String(a.backstory).trim().slice(0,2000);
 if(a.onboardingComplete===true)s.onboardingComplete=true;
 if(v.provider!==undefined||v.providerPort!==undefined||v.providerUrl!==undefined){const url=v.providerUrl!==undefined?cleanProviderUrl(v.providerUrl):s.settings.providerUrl||'';const p=providerConfig(v.provider||s.settings.provider||'ollama',v.providerPort??s.settings.providerPort,url);s.settings.provider=p.id;s.settings.providerPort=p.port;s.settings.providerUrl=p.hosted?'':url;}
 for(const key of ['world','model'])if(v[key]!==undefined)s.settings[key]=String(v[key]).slice(0,key==='world'?2000:100);for(const key of ['useModel','weekends','sound'])if(v[key]!==undefined)s.settings[key]=!!v[key];const start=v.startHour===undefined?s.settings.startHour:+v.startHour,end=v.endHour===undefined?s.settings.endHour:+v.endHour;if(!Number.isInteger(start)||!Number.isInteger(end)||start<0||end>24||start>=end)throw Error('Work hours must start before they end (0–24).');s.settings.startHour=start;s.settings.endHour=end;if(a.name)s.name=String(a.name).trim().slice(0,40);break;}
 case 'rest':s.settings.restOverride=false;if(s.battle&&!s.battle.pausedAt)s.battle.pausedAt=now.getTime();s.energy=100;entry(s,'Returned to camp. Nothing to catch up on.');break;
 case 'override':s.settings.restOverride=true;break;
 default:throw Error('Unknown action.');
 }actionBeat(s,a,t);syncLeader(s);return s;
}
export function publicState(s,now=new Date()){return {...s,level:levelFor(s.xp),resting:resting(s,now),catalog:[...items,...(s.squad?.chapterItems||[])]};}
