import {characterQuestion} from './character-depth.js';
export function ensureLore(s){s.lore??={answers:[],cursor:0,nextAt:1,revision:0};}
export function loreAction(s,a){ensureLore(s);if(!['character-answer','character-later','character-skip','character-edit'].includes(a.type))return false;const l=s.lore;if(a.expectedLoreRevision!==l.revision||a.leaderId!==(s.squad?.activeAdventurer||'founder'))throw Error('This character changed in another tab. Reopen their story to continue.');if(a.type==='character-answer'){const q=characterQuestion(s);if(a.id!==q.id)throw Error('That question has already moved on.');const answer=String(a.answer||'').trim();if(!answer)throw Error('Write a little about your adventurer, or choose “Another time”.');l.answers.push({...q,answer:answer.slice(0,500),chapter:s.world.chapter});l.cursor++;l.nextAt=s.world.totalWins+3;}if(a.type==='character-edit'){const old=l.answers.find(x=>x.id===a.id);if(!old)throw Error('That memory is not part of this character’s story.');const answer=String(a.answer||'').trim();if(!answer)l.answers=l.answers.filter(x=>x.id!==a.id);else old.answer=answer.slice(0,500);}if(a.type==='character-skip'){l.cursor++;l.nextAt=s.world.totalWins;}if(a.type==='character-later')l.nextAt=s.world.totalWins+3;l.revision++;s.profileRevision=(s.profileRevision||0)+1;return true;}
const stop=new Set('the a an and or but to of in on at for with from as is are was were be been their they them his her he she its it this that you your once again very just into through toward under over one two small little then while not has have had will would could should by all more than still like own each'.split(' '));
const words=text=>String(text).toLowerCase().match(/[a-z]+(?:['’][a-z]+)?/g)||[];
const plain=text=>words(text).map(w=>w.length>4?w.replace(/s$/,''):w).join(' ');
export function recentBeats(s,event){const all=s.world?.beats||[];const i=event?all.findIndex(b=>b.id===event.id):-1;return all.slice(i>=0?i+1:0,i>=0?i+13:12);}
export function tiredMotifs(s,event){const recent=recentBeats(s,event).slice(0,8),counts=new Map(),important=plain([s.name,s.world.mission.title,s.world.mission.hook,...Object.values(s.world.relationships).map(r=>r.name)].join(' '));for(const b of recent){const w=words(b.text).map(x=>x.length>4?x.replace(/s$/,''):x),seen=new Set();for(let i=0;i<w.length;i++){if(!stop.has(w[i])&&w[i].length>4)seen.add(w[i]);if(i&& !stop.has(w[i-1])&&!stop.has(w[i]))seen.add(w[i-1]+' '+w[i]);}for(const phrase of seen)if(!important.includes(phrase))counts.set(phrase,(counts.get(phrase)||0)+1);}return [...counts].filter(([p,n])=>n>=(p.includes(' ')?2:3)).sort((a,b)=>b[1]-a[1]).slice(0,20).map(([p])=>p);}
export function characterContext(s,event){ensureLore(s);const recent=plain(recentBeats(s,event).slice(0,5).map(b=>b.text).join(' ')),answers=s.lore.answers;const used=t=>words(t).filter(w=>!stop.has(w)&&w.length>=3).filter(w=>recent.includes(plain(w))).length>=2;const available=answers.filter(a=>a.theme!=='boundaries'&&!used(a.answer));const pick=available.length?available[(s.world.beats.length+s.world.chapter)%available.length]:null;const backstoryUsed=used(s.backstory||'');return {identity:s.name,appearance:'Use the existing small humanoid avatar: one head, two arms and two legs. Hair, clothes, and equipped gear may be described. Origin, tastes, and metaphors do NOT imply anatomy. No invented tentacles, claws, wings, horns, extra limbs, or transformations for the adventurer.',backstory:backstoryUsed?'Background has already been foregrounded recently. Leave it in the background for this beat.':s.backstory,characterDetail:pick?{question:pick.text,answer:pick.answer}:'No personal detail is needed in this beat. Draw on the place, an NPC’s goal, a consequence, or a discovery.',boundaries:answers.filter(a=>a.theme==='boundaries').map(a=>a.answer),avoidRepeating:tiredMotifs(s,event)};}
export function validateStory(s,event,text){const normalized=plain(text);const motifs=tiredMotifs(s,event);if(motifs.some(m=>(' '+normalized+' ').includes(' '+m+' ')))throw Error('This story repeats an overused motif.');const escaped=s.name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const anatomy=new RegExp(`(?:${escaped}(?:['’]s)?|their|his|her|your)\\s+(?:[a-z-]+\\s+){0,3}(?:tentacles?|claws?|clawed|wings?|horns?|tails?|extra limbs?)\\b`,'i');if(anatomy.test(text)||/tentacle[- ]guide/i.test(text))throw Error('The story invented anatomy that is not in the avatar.');const current=new Set(words(text).filter(w=>!stop.has(w)));for(const b of recentBeats(s,event).slice(0,5)){const prev=new Set(words(b.text).filter(w=>!stop.has(w)));const union=new Set([...current,...prev]);const overlap=[...current].filter(w=>prev.has(w)).length;if(union.size&&overlap/union.size>.65)throw Error('This story is too similar to a recent beat.');}return text;}
