// The world bank: shared mad-lib pools for the built-in adventures. Any adventure
// line may use these placeholders, and adventures can also carry their own `vars`.
// Values are rolled once per chapter so a story stays consistent, and a replayed
// adventure gets a fresh mix. test/adventures.test.ts checks each sentence form.
export const sharedVars = {
  // A friendly local, a name plus a role: "{helper} says…", "you ask {helper}".
  helper: ["Amara the beekeeper", "Old Tobin the ferryman", "Priya the lamplighter", "Grandpa Ezra the clock mender", "Mei the kite maker", "Luca the cheesemonger", "Nana Odette the quilter", "Kofi the bridge keeper", "Ines the herbalist", "Young Rafi the messenger", "Hazel the candle maker", "Bartholomew the bell ringer", "Suki the tea brewer", "Mother Agnes the gardener", "Tomas the tinker", "Leilani the net weaver", "Oskar the chimney sweep", "Zara the map seller", "Auntie Bea the jam maker", "Dmitri the fiddler", "Noor the lantern seller", "Little Pim the goat herder", "Magnus the woodcarver", "Yuki the paper folder", "Grandma Rosa the storyteller", "Emeka the potter", "Fern the postmistress", "Old Silas the shepherd", "Anouk the florist", "Hamid the spice trader", "Clementine the innkeeper", "Kai the boat builder", "Marisol the weaver", "Jonah the apple picker", "Ottilie the hatmaker", "Sanjay the stargazer", "Willa the mushroom forager", "Barnaby the cobbler", "Ayesha the bookbinder", "Old Mags the lock keeper", "Teodor the glassblower", "Lottie the goose girl", "Rowan the gatekeeper", "Chen the noodle maker", "Esme the seamstress", "Grandpa Idris the fisherman", "Pilar the orchard keeper", "Felix the wheelwright", "Tansy the soap maker", "Mateo the lighthouse keeper", "Imogen the librarian", "Old Ansel the miller", "Kiri the rope maker", "Dorothea the dressmaker", "Arlo the stable hand", "Nadia the baker", "Sparrow the errand runner", "Björn the blacksmith", "Opal the button maker", "Uncle Jun the dumpling cook", "Ivy the hedge trimmer", "Maeve the harpist", "Tariq the carpet mender", "Posy the flower seller", "Old Gideon the tollkeeper", "Lina the weather watcher", "Rudi the pretzel baker", "Hana the calligrapher", "Cosmo the juggler", "Delphine the perfumer", "Ezinne the dyer", "Percival the pigeon keeper", "Juniper the tree climber", "Saoirse the cartwright", "Ravi the lantern mender", "Old Winnie the knitter", "Theo the hedge wizard", "Ximena the chocolatier", "Gus the grocer", "Bettina the snail racer"],
  // A small settlement’s proper name: "in {village}", "to {village}".
  village: ["Thimbledown", "Kettlewick", "Mossmere", "Little Hobbling", "Crumbleton", "Pennywhistle", "Fernbottle", "Dapplewood", "Button Hollow", "Teacup Rise", "Muddlecombe", "Lower Snoozing", "Wobbleford", "Bumblethorpe", "Marrowmead", "Hearthwick", "Sprocketby", "Tumbledown Cross", "Pipkin Green", "Nutshell End", "Gooseberry Knoll", "Cobblenook", "Lanternby", "Candlemoss", "Drowsy Dell", "Pebblecrook", "Hollyhock Bend", "Figgleton", "Mizzlemoor", "Brackenbell", "Periwinkle Quay", "Saltbiscuit", "Gingerholt", "Quillby", "Tuppence Row", "Mapleknot", "Snugbury", "Crumpet Hill", "Lilypad Landing", "Dunnock Green", "Twiddlecombe", "Oakapple Cross", "Spindleford", "Fogglewick", "Mumblebee", "Caraway Corner", "Hobnob Hill", "Willowmint", "Puddingstone", "Little Dumpling"],
  // A named local feature with "the": "near {landmark}".
  landmark: ["the Crooked Well", "the Old Toll Bridge", "the Leaning Lantern Post", "the Mossy Stepping Stones", "the Hundred-Stair Tower", "the Tea-Kettle Spring", "the Wishing Oak", "the Button Market", "the Round Red Barn", "the Half-Moon Pond", "the Old Mill Wheel", "the Singing Weathervane", "the Upside-Down Boathouse", "the Bramble Maze", "the Clock Tower Steps", "the Lopsided Lighthouse", "the Cobbled Square", "the Fox-Ear Rocks", "the Honeycomb Cliffs", "the Painted Gate", "the Mushroom Ring", "the Snail Post Office", "the Crooked Signpost", "the Willow Tunnel", "the Frog Choir Pond", "the Quiet Orchard", "the Three Kettles Inn", "the Bell Meadow", "the Mapmaker’s Arch", "the Rope Swing Oak", "the Lantern Stair", "the Tumbled Wall", "the Kite-Flying Meadow", "the Sunflower Field", "the Glass Greenhouse", "the Old Stone Oven", "the Sheep Bridge", "the Hollow Log Bridge", "the Copper Fountain", "the Wobbly Pier", "the Owl Tower", "the Star Well", "the Buttercup Meadow", "the Mossy Milestone", "the Rain Barrel Corner", "the Patchwork Fields", "the Crooked Chimney", "the Bakery Steps", "the Peppermint Falls", "the Snoring Cave", "the Cloudberry Slopes", "the Sundial Garden", "the Tallest Haystack", "the Toadstool Bridge", "the Library Stump", "the Weathered Windmill", "the Village Green", "the Humming Beehives", "the Seashell Grotto", "the Whistling Reeds"],
  // A small animal with "a": "you spot {critter}".
  critter: ["a curious hedgehog", "a pair of gossiping magpies", "a sleepy dormouse", "a nosy goose", "a pair of squabbling sparrows", "an inquisitive otter", "a very round robin", "a shy badger", "a velvet-eared bunny", "a snoozing tabby cat", "a hopeful little fox cub", "a snail with a painted shell", "a busy bumblebee", "a pair of dancing moths", "a grumpy old toad", "a chatty parrot", "a family of field mice", "a patient heron", "a ladybird with extra spots", "a curious lamb", "a pair of cooing pigeons", "an owl in tiny spectacles", "a bossy speckled hen", "a friendly newt", "a ginger kitten", "a waddling puffin", "a red squirrel with full cheeks", "a wise old tortoise", "a playful seal pup", "a mole with muddy paws", "a cheerful wren", "a goat wearing a bell", "an overexcited terrier", "a pair of hopping frogs", "a sleepy sheepdog", "a bright little firefly", "a fluffy snow hare", "a crab wearing a bottle cap", "a raccoon with sticky paws", "a very polite crow", "an elderly beaver", "a glow-worm with a night-light", "a lizard sunning on a rock", "a hovering hummingbird", "a mischievous ferret", "a stripy chipmunk", "a fuzzy snowy owl chick", "an armadillo in a hurry", "a lanky stork", "a duckling who won’t stop quacking"],
  // A small object with "a": "you find {trinket}".
  trinket: ["a brass thimble", "a blue glass button", "a silver acorn charm", "a tiny brass key", "a cracked pocket compass", "a ribbon-tied letter", "an amber marble", "a little copper bell", "a pressed four-leaf clover", "a wooden whistle", "a painted pebble", "a spool of gold thread", "a snow globe with no snow", "a moth-shaped brooch", "a clockwork beetle", "an owl-shaped teapot lid", "a star-shaped cookie cutter", "a velvet coin purse", "a bent silver spoon", "a map drawn on a napkin", "a tin wind-up mouse", "a feather quill", "a pocket watch that runs slow", "a bottle with a note inside", "an old library card", "a hand-knit mitten", "a jar of pickled starlight", "a seashell that hums", "a candle stub", "a crocheted daisy", "a jade frog figurine", "a wooden yo-yo", "a harmonica with one good note", "a folded paper crane", "a small brass telescope", "a heart-shaped locket", "a key ring with no keys", "an embroidered handkerchief", "a chipped teacup", "a smooth river stone", "a sugar cube wrapped in foil", "a worn wooden die", "a thumb-sized book", "a ceramic snail", "a cork with a face drawn on", "a ball of blue yarn", "a tiny paper crown", "a sprig of dried lavender", "a seed packet labeled “maybe”", "an umbrella sized for a mouse"],
  // Something to share, as an object: "shares {snack}", "over {snack}".
  snack: ["warm honey buns", "a thermos of cocoa", "buttered crumpets", "a pot of mint tea", "cinnamon twists", "a basket of ripe plums", "toasted marshmallows", "a wedge of crumbly cheese", "blackberry tarts", "a flask of spiced cider", "roasted chestnuts", "lemon shortbread", "a bag of sugared almonds", "apple butter on warm toast", "ginger biscuits", "a slice of carrot cake", "cheese scones", "a pot of jasmine tea", "fig rolls", "cardamom buns", "a tin of oat cookies", "steamed dumplings", "a pear and walnut loaf", "maple fudge", "a thermos of barley soup", "peppermint creams", "a stack of pancakes", "strawberry jam sandwiches", "hot buttered corn", "cherry hand pies"],
  // A noun phrase that reads after "under": "under {weather}".
  weather: ["a soft drizzle", "a pink evening sky", "a sky full of fluffy clouds", "a lazy afternoon sun", "a sprinkle of first snow", "a thin silver mist", "a lemon-yellow sunrise", "a bright blue sky", "a patter of warm rain", "a big round harvest moon", "a scatter of early stars", "a thick quilt of cloud", "a sky the color of peaches", "a flurry of feathery snow", "a honey-gold sunset", "a crisp frosty sky", "a passing sunshower", "a dove-gray sky", "a wide starry sky", "a faint double rainbow"],
  // A time of day that reads after "by" or "until": "by {hour}".
  hour: ["teatime", "dusk", "lantern-lighting time", "sunrise", "midmorning", "noon", "suppertime", "bedtime", "moonrise", "the first evening star", "elevenses", "the last ferry"],
};

export const RESERVED_VARS = ['foe', 'place', ...Object.keys(sharedVars)];
