import {drawSquad,drawHome} from './squad-art.js';
import {drawScene} from './scenes.js';
import {hairstyles,normalizeAppearance} from './character.js';
const palette={'.':null,o:'#26342c',h:'#d8ba80',f:'#f4d29b',d:'#9d714b',g:'#aac77a',c:'#668e57',b:'#3e6048',s:'#c2d2be',w:'#f4e9b1',k:'#283b31'};
const hero=['................','......ffff......','.....ffffff.....','.....ffffff.....','.....fokoff.....','.....ffffff.....','......ffff......','.......ff.......','...ooocccooo....','..osocgggcoco...','..osocgggcoco...','..os.occcco.f...','..os..odd...f...','..os..odd.......','......ododo.....','.....okk.kk.....'];
const imp=['................','....gg....gg....','...gggggggggg...','..ggccggccgggg..','.gggwggggwggggg.','.gggwggggwggggg.','.gggggddggggggg.','..gggddddggggg..','...gggggggggg...','..gggggggggggg..','.gggggggggggggg.','gg..gggggggg..gg','....gggggggg....','....gg..gggg....','...ggg...gggg...','................'];
export function drawSprite(ctx,kind,x,y,scale=2,equipped={},appearance={}){const sprite=kind==='hero'?hero:imp;const colors={...palette};if(kind==='hero'){const a=normalizeAppearance(appearance);colors.f=a.skinColor;colors.g=a.shirtColor;colors.c=a.shirtColor;colors.d=a.pantsColor;const gear={...Object.fromEntries([['moss-cloak','#648856'],['moon-cloak','#8073a5'],['tide-cloak','#77b8c5'],['dusk-cloak','#aa80ce'],['ember-blade','#f3aa68'],['star-blade','#b4e6fa'],['frost-blade','#d1f3ef'],['dawn-blade','#ffe39d']])};if(equipped.cloak)colors.c=equipped.cloakColor||gear[equipped.cloak]||colors.c;if(equipped.weapon)colors.s=equipped.weaponColor||gear[equipped.weapon]||colors.s;}else{colors.g='#95b865';colors.c='#5e8b48';colors.w='#f4db8a';}sprite.forEach((row,ry)=>[...row].forEach((p,rx)=>{if(colors[p]){ctx.fillStyle=colors[p];ctx.fillRect(Math.floor(x+rx*scale),Math.floor(y+ry*scale),scale,scale);}}));if(kind==='hero'){const a=normalizeAppearance(appearance);ctx.fillStyle=a.hairColor;for(const [hx,hy,hw,hh]of hairstyles.find(h=>h.id===a.hairStyle).pixels)ctx.fillRect(x+hx*scale,y+hy*scale,hw*scale,hh*scale);}
if(kind==='hero'&&equipped.hat){ctx.fillStyle=equipped.hatColor||({'sun-crown':'#f4d56a','fern-crown':'#a2ca86','amber-crown':'#e7a664'})[equipped.hat];ctx.fillRect(x+4*scale,y,7*scale,2*scale);[4,7,10].forEach(i=>ctx.fillRect(x+i*scale,y-2*scale,scale,3*scale));}}
export function icon(kind){const shapes={tea:'<path fill="#b3c58c" d="M5 5h7v3H5z"/><path fill="#9bb886" d="M4 9h10v7H4z"/><path fill="#d9d597" d="M5 8h7v2H5z"/><path fill="#dadbb8" d="M14 10h3v4h-3z"/><path fill="#ccdbb8" d="M6 1h1v3H6zm4 0h1v3h-1z"/>',weapon:'<path fill="#cedabe" d="M12 1h4v4h-2v2h-2v2h-2v2H8V7h2V5h2z"/><path fill="#e6c176" d="M5 8h2v2h2v2h2v2H9v-2H7v-2H5z"/><path fill="#a78554" d="M4 12h3v3H4zM2 15h3v3H2z"/>',cloak:'<path fill="#b0bbdf" d="M7 2h6v2h2v4h2v8H3V8h2V4h2z"/><path fill="#8276ad" d="M9 5h2v9H9zM3 16h5v2H3zm9 0h5v2h-5z"/>',hat:'<path fill="#e8c576" d="M3 5h2v3h3V3h3v5h3V5h3v10H3z"/><path fill="#bd8b53" d="M3 13h14v3H3z"/>',gem:'<path fill="#b4c8dc" d="M6 2h7l4 6-7 10L2 8z"/><path fill="#829ab3" d="M2 8h15l-7 10z"/><path fill="#d8e5eb" d="M6 2h4L6 8H2z"/>',fire:'<path fill="#e0a05c" d="M10 1v4h3v3h2v3h2v5H3v-5h2V8h2V5h1V1z"/><path fill="#f5d77e" d="M9 8h2v3h2v5H7v-5h2z"/>',leaf:'<path fill="#b9cd8c" d="M3 7h3V4h4V2h7v7h-2v3h-3v2H7v-2H4z"/><path fill="#718b51" d="M3 16h2v-2h2v-2h2v-2h2V8h2V6h-2v2H9v2H7v2H5v2H3z"/>'};return `<svg viewBox="0 0 20 20" aria-hidden="true" shape-rendering="crispEdges">${shapes[kind]||shapes.gem}</svg>`;}
let raf;export function stopArt(){cancelAnimationFrame(raf);}export function startArt(state){stopArt();const canvas=document.querySelector('#scene'),portrait=document.querySelector('#portrait'),squad=document.querySelector('#squad-scene'),home=document.querySelector('#home-scene');if(!canvas&&!portrait&&!squad&&!home)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let last=0;
function render(time){if(time-last<1000/12&&!reduced){raf=requestAnimationFrame(render);return;}last=time;const t=reduced?0:time/1000;if(portrait){const p=portrait.getContext('2d');p.clearRect(0,0,100,125);p.fillStyle='#101c1777';p.fillRect(22,108,58,7);drawSprite(p,'hero',19,34+Math.round(Math.sin(t*2)),4,state.equipped,state.appearance);}
if(home)drawHome(home.getContext('2d'),state,drawSprite,t);if(squad)drawSquad(squad.getContext('2d'),state,drawSprite,t);if(canvas){canvas.width=480;canvas.height=194;const c=canvas.getContext('2d');c.imageSmoothingEnabled=false;drawScene(c,state,t,drawSprite,reduced);}if(!reduced)raf=requestAnimationFrame(render);}
raf=requestAnimationFrame(render);}
