import {bindGoogleCalendar} from './google-calendar-ui.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bridge=()=>window.webkit?.messageHandlers?.sidequestCalendar;
const native=async body=>{if(!bridge())throw Error('Open the Sidequest desktop app to connect calendars.');return bridge().postMessage(body);};
export function dayEvents(s,day=new Date()){const start=new Date(day);start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1);return (s.calendar?.events||[]).filter(e=>e.start<+end&&e.end>+start).sort((a,b)=>Number(b.allDay)-Number(a.allDay)||a.start-b.start);}
function rows(s,events){return events.map(e=>{const linked=s.tasks.find(t=>t.calendarEventId===e.id);return `<article class="agenda-event"><div class="agenda-time">${e.allDay?'ALL DAY':new Date(e.start).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</div><div><h3>${esc(e.title)}</h3><p>${esc(e.calendarName)}${e.location?' · '+esc(e.location):''}</p>${!e.allDay?`<small>Until ${esc(new Date(e.end).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}))}</small>`:''}</div><button class="subtle" data-calendar-quest="${e.id}" ${linked?'disabled':''}>${linked?'Quest added':'Make a quest'}</button></article>`;}).join('');}
function freshness(c){return c?.lastSync?`Updated ${new Date(c.lastSync).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}`:'Not synced yet';}
export function agendaCard(s){const c=s.calendar;if(!c?.enabled)return '';const events=dayEvents(s);return `<section class="card agenda-card"><div class="section-heading"><h2>Today’s waypoints</h2><button class="subtle" data-page="agenda">Full agenda →</button></div><p class="help">Today’s meetings become quests automatically when enabled. Complete them to earn XP and loot.</p>${c.error?`<p class="calendar-error">${esc(c.error)} · Showing the last saved schedule.</p>`:''}${rows(s,events.slice(0,4))||'<p class="help">Nothing scheduled today in your saved calendars.</p>'}${events.length>4?`<button class="subtle" data-page="agenda">${events.length-4} more events →</button>`:''}<small class="calendar-updated">${esc(freshness(c))}</small></section>`;}
export function agendaPage(s){const c=s.calendar,days=[];for(let i=0;i<14;i++){const day=new Date();day.setDate(day.getDate()+i);const events=dayEvents(s,day);if(events.length)days.push(`<section class="card agenda-day"><h2>${i===0?'Today':i===1?'Tomorrow':esc(day.toLocaleDateString([],{weekday:'long',month:'short',day:'numeric'}))}</h2>${rows(s,events)}</section>`);}return `<section class="card agenda-intro"><span class="eyebrow">YOUR REAL-WORLD WAYPOINTS</span><h2>A little room for the day.</h2><p>Connect Google Calendar directly, or use calendars already on your Mac. Today’s meetings become quests automatically from the calendars you choose.</p><div class="support-buttons"><button class="primary" data-google-calendar>${s.googleCalendar?.connected?'Choose Google calendars':'Connect Google Calendar'}</button><button class="secondary" data-calendars>Use Mac calendars instead</button>${s.googleCalendar?.connected?'<button class="subtle" data-google-disconnect>Disconnect Google</button>':''}${c?.enabled?'<button class="secondary" data-calendar-refresh>Refresh now</button><button class="subtle" data-calendar-disconnect>Disconnect & clear schedule</button>':''}</div><p class="help">Read-only · next 14 days · refreshes every 15 minutes while this desktop app is open. Timed events for today become quests automatically when enabled; all-day events stay optional. Complete a meeting quest to earn the usual rewards. Completing it never changes the original event.</p>${c?.enabled?`<label class="check"><input type="checkbox" data-calendar-auto ${c.autoQuests!==false?'checked':''}>Automatically turn today’s meetings into quests</label><p class="help">${esc(c.selected.map(x=>x.name).join(' · '))} · ${esc(freshness(c))}</p>`:''}${c?.error?`<p class="calendar-error">${esc(c.error)} Your last saved schedule is shown below.</p>`:''}</section>${days.join('')||'<section class="card agenda-day"><p>No upcoming events in your saved schedule yet.</p></section>'}`;}
let syncing=false,lastAttempt=0;
export async function syncCalendars({getState,request,update},force=false){const c=getState()?.calendar;if(syncing||!c?.enabled||(c.provider!=='google'&&!bridge())||(!force&&Date.now()-Math.max(lastAttempt,c.lastSync||0)<900000))return;syncing=true;lastAttempt=Date.now();const revision=c.revision;try{let next;if(c.provider==='google'){next=await request('google',{operation:'sync',expectedCalendarRevision:revision});}else{const data=await native({operation:'events',ids:c.selected.map(x=>x.id)});next=await request('action',{type:'calendar-sync',expectedCalendarRevision:revision,events:data.events});}update(next);return true;}catch(e){const message=String(e.message||e);try{const next=await request('action',{type:'calendar-error',expectedCalendarRevision:revision,error:message});update(next);}catch{}if(force)throw Error(message);}finally{syncing=false;}}
export function bindCalendars({getState,request,update,act,modal,toast}){
 bindGoogleCalendar({getState,request,update,modal,toast});
 const s=getState();const config={getState,request,update};const all=(selector,fn)=>document.querySelectorAll(selector).forEach(fn);
 all('[data-calendar-auto]',b=>b.onchange=()=>act('calendar-auto',{enabled:b.checked,expectedCalendarRevision:getState().calendar.revision}));
 all('[data-calendar-refresh]',b=>b.onclick=async()=>{if(getState().calendar.provider!=='google'&&!bridge())return toast('Refresh calendars from the Sidequest desktop app.');b.disabled=true;try{await syncCalendars(config,true);}catch(e){toast(e.message);}finally{b.disabled=false;}});
 all('[data-calendar-disconnect]',b=>b.onclick=()=>act('calendar-disconnect',{expectedCalendarRevision:getState().calendar.revision}));
 all('[data-calendar-quest]',b=>b.onclick=()=>act('calendar-quest',{id:b.dataset.calendarQuest}));
 all('[data-calendars]',b=>b.onclick=()=>{
  modal('Connect Mac calendars',`<div class="calendar-connect"><p>In the Mac Calendar app, choose <strong>Calendar → Add Account → Google</strong> (or your provider), sign in, and enable Calendars. Then choose your calendars below.</p><p class="help">Subscribed calendar feeds also work when added to Mac Calendar. You don’t need to publish a private calendar or paste a secret link here.</p><p class="help">macOS calls the permission “full access” because reading events requires it. Sidequest only reads your selected calendars. It never creates, edits, or deletes calendar events.</p>${bridge()?'<button class="primary" data-calendar-list>Choose from my Mac’s calendars</button>':'<p class="calendar-error">Calendar connection is available in the Sidequest desktop app. This browser preview can display its saved schedule.</p>'}<p class="help">Only event titles, times, calendar names, and locations are saved locally. Notes and attendees are not imported. Today’s timed events automatically become quests and their titles may be used by your configured local storyteller. You can turn automatic quests off in Agenda. Notes and attendees stay out of stories.</p><div data-calendar-picker></div><p class="inline-error" data-calendar-status role="status"></p></div>`);
  const dialog=document.querySelector('#modal'),load=dialog.querySelector('[data-calendar-list]');if(!load)return;
  load.onclick=async()=>{load.disabled=true;const status=dialog.querySelector('[data-calendar-status]');status.textContent='Looking for your calendars…';try{const data=await native({operation:'list',requestAccess:true});if(!dialog.open)return;status.textContent='';const c=getState().calendar||{revision:0,selected:[]};const revision=c.revision;const calendars=data.calendars;
   dialog.querySelector('[data-calendar-picker]').innerHTML=`<form class="calendar-picker">${calendars.map((x,i)=>`<label class="check"><input type="checkbox" name="calendar" value="${i}" ${c.selected.some(y=>y.id===x.id)?'checked':''}><span>${esc(x.name)}<small>${esc(x.account)}</small></span></label>`).join('')||'<p>No calendars found. Add an account to Mac Calendar and try again.</p>'}<button class="primary" type="submit">Use selected calendars</button></form>`;
   dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{const selected=[...new FormData(e.target).getAll('calendar')].map(i=>calendars[+i]);const next=await request('action',{type:'calendar-select',expectedCalendarRevision:revision,calendars:selected});update(next);if(selected.length)await syncCalendars(config,true);dialog.close();}catch(e){status.textContent=e.message;}finally{button.disabled=false;}};
  }catch(e){status.textContent=String(e.message||e);}finally{load.disabled=false;}};
 });
}
